### ISSUE TITLE
Payload window ignores keyboard input in windows burp installation

### ISSUE THREAD

**Issue by garthoid** [RUB-NDS/BurpSSOExtension#3]
Linux works fine. 

I cannot edit the payload window with the keyboard, but I can work around this just by using the mouse and using the context menu.  I have to copy and paste any changes I need. The linux version allows keyboard input. Other elements of burp allow keyboard input.

**Comment by TimGuenther** [comment]
Hi, I had the same problem but with a different keyboard layout under linux. It seems that ```RSyntaxTextArea``` has a problem with it, we can't solve the issue until now.

Unfortunately I can't find the forum entry, with quick googleing.
Maybe you have more luck.

**Comment by TimGuenther** [comment]
This is the entry: http://fifesoft.com/forum/viewtopic.php?f=4&t=682 they got only workarounds. If you have some time take a look at it. At the moment I don't have enough time to fix it. Maybe you want to help or @CheariX has some ideas.

**Comment by garthoid** [comment]
Thanks for responding. I will see what I can do.
