### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by putsi** [RUB-NDS/BurpSSOExtension#4]
Hi, I found a vulnerability on this extension. The vulnerability exists in the EsPReSSO version that is on the BApp Store (1.0?) and also on the latest release (2.0.1) on Github.
How would you like me to report it? 
Please provide the appropriate contact information or instructions for where to report it.

**Comment by CheariX** [comment]
Hi,
thanks for this information. You have been contacted by mail.
